### PR TITLE
Fix wrong url on worker

### PR DESCRIPTION
**Pull request by sebestenyb**
https://github.com/dusterio/laravel-aws-worker/issues/1

### CODE REVIEW

**Comment by gbwashleybrown** [comment]
Could you please merge this @dusterio ???

**Comment by hbouhadji** [comment]
Hello,

any news about this PR ?

Thanks

**Comment by dusterio** [comment]
@hbouhadji hmm shouldn't this be in the AppServiceProvider of the app?

**Comment by hbouhadji** [comment]
@dusterio Correct, I got it working like that, thanks

**Comment by fylzero** [comment]
As called out here and in the original issue - URL::forceRootUrl(config('app.url')); should simply be added to the AppServiceProvider.

**Pull request closed without merging**
